baseResources:
  ingress:
    host: reader.paul-steele.com
    port: 80
  service:
    port: 80
  deployment:
    containers:
    - image: freshrss/freshrss:1.17.0
      name: freshrss
      ports:
      - 80
      envs:
      - name: CRON_MIN
        value: "5, 35"
      volumeMounts:
      - config
      - extensions
  volumes:
  - name: config
    source:
      nfs: /srv/nfs/freshrss/data
    mountPath: /var/www/FreshRSS/data
  - name: extensions
    source:
      nfs: /srv/nfs/freshrss/extensions
    mountPath: /var/www/FreshRSS/extensions
