nginx-ingress:
  controller:
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    extraArgs: {
      default-ssl-certificate: "default/paul-steele.com"
    }
    config:
      enable-modsecurity: "true"
      enable-owasp-modsecurity-crs: "true"
      enable-access-log-for-default-backend: "true"
      access-log-path: "/logs/root.log"
    nodeSelector:
      kubernetes.io/hostname: minecraft
    extraVolumeMounts:
    - name: logs
      mountPath: /logs
    extraVolumes:
    - name: logs
      hostPath:
        path: /srv/nfs/nginx/logs
    service:
      loadBalancerIP: "192.168.0.200"
