apiVersion: v2
name: nfs-client-provisioner
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: 1.15.0
dependencies:
- name: nfs-subdir-external-provisioner
  version: 4.0.11
  repository: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
