repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: jetstack
  url: https://charts.jetstack.io
- name: eddycharly
  url: https://eddycharly.github.io/tekton-helm
- name: itzg
  url: https://itzg.github.io/minecraft-server-charts/
releases:
- name: automation
  namespace: default
  chart: ./charts/nodered
- name: backup
  namespace: default
  chart: ./charts/duplicati
- name: books
  namespace: default
  chart: ./charts/calibre
- name: ci
  namespace: default
  chart: ./charts/tekton
  hooks:
  - events: ["prepare"]
    showlogs: true
    command: sh
    args: ["-c", "./tools/filter-crds.sh ./charts/tekton/charts/*"]
  values:
  - ./charts/tekton/rbac.yaml
  - ./charts/tekton/pipeline.yaml
  secrets:
  - ./charts/tekton/secrets.yaml
- name: certificates
  namespace: default
  chart: ./charts/certmanager
  secrets:
  - ./charts/certmanager/secrets.yaml
- name: containers
  namespace: default
  chart: ./charts/docker-registry
- name: database
  namespace: default
  chart: ./charts/mysql
  secrets:
  - ./charts/mysql/secrets.yaml
- name: files
  namespace: default
  chart: ./charts/nextcloud
  secrets:
  - ./charts/nextcloud/secrets.yaml
- name: finance
  namespace: default
  chart: ./charts/firefly
  secrets:
  - ./charts/firefly/secrets.yaml
- name: home
  namespace: default
  chart: ./charts/homeassistant
- name: minecraft
  namespace: default
  chart: ./charts/minecraft
- name: ingress
  namespace: default
  chart: ./charts/nginx
- name: loadbalancer
  namespace: default
  chart: ./charts/metallb
- name: monitoring
  namespace: default
  chart: ./charts/prometheus
- name: music
  namespace: default
  chart: ./charts/subsonic
- name: passwords
  namespace: default
  chart: ./charts/bitwarden
- name: reader
  namespace: default
  chart: ./charts/freshrss
- name: issues
  namespace: default
  chart: ./charts/jira
- name: sso
  namespace: default
  chart: ./charts/authelia
  secrets:
  - ./charts/authelia/secrets.yaml
- name: storage
  namespace: default
  chart: ./charts/nfs-client-provisioner
- name: deployments
  namespace: deployments
  chart: ./charts/deployments
  secrets:
  - ./charts/deployments/secrets.yaml
