baseResources:
    secrets:
    -   name: ENC[AES256_GCM,data:YKWm+XJFyVj0Lko1tUfqrN/YQfI=,iv:Oyq4e9LwDIIlxL8Ln3br3w714dzEwyok4to/y4JVM94=,tag:kCN8YBe+uD/H+cBJOD5usQ==,type:str]
        fields:
            user: ENC[AES256_GCM,data:08i4yHYcdg==,iv:S1xErRV5dn3s3hSV9ohTF+qDuIvjHh987pT1Zo9/T4A=,tag:TriBiBcq/F8M6hAF02BjeA==,type:str]
            password: ENC[AES256_GCM,data:4URQ6wPJ+soEL+GPAV0uTvwyFdGVCTmg7hnaWC5mEhzrl/FBun2pAHOUUlUCAMJQ2w==,iv:afjob4cEwT0rOUCaUIfj4vcZ0f+o7+TfZ8+AIlxXZxI=,tag:OAvfyJ96txOj4DvX6HeMAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-06-26T13:52:23Z'
    mac: ENC[AES256_GCM,data:tiv0woUOYqml2B/Tw2C4k/9d6+rpJFIdxfuHgz24npW8ooNQfAhtLxjHgitUENMsCCL/53C9fL0fsGFwMEpIEp7q4fuSqz5KCjWJdkCV5Jy1z9DIu0OD2LPpcZiaUzHSoOyAGlKQjl4ANlya4+51Yw97aCOtRdt8ARi74C3+0Pc=,iv:SEi8klnrRmYVxyPlWDe81QJLJEv9UX7nT+A24NlMWt8=,tag:PrKB9Ff+IcE0LNwo99VnKA==,type:str]
    pgp:
    -   created_at: '2021-06-26T13:52:23Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA1Biv9gnCd8SAQf/W7EomV94Vno3J1ugICXux12czRRQqO4dRjIwc55umM2h
            MpiJIF7b7dt/vYi7wvrwZeiP/0O3vKEIcTbT0gfKss7+0NYhQ+kNsX74I7GiXrUM
            xCHW+VdUJyFNjDTK8fmd2SW3b2xcYc3eYPCh1ta6AvBOwy8xX1oS89RdIIEzibuA
            6as4Ox6jgIn8vCMUzQd03sAmpd/cctPhRngzdTVttVTpJCF4KQ120cBtXPuyEj5W
            kQ2MaMn+TVYDdLxSOxSLAXe1s+x2e+rioMLLTeQcoBuxGPs/SEsG1KJ5AusJO3Ay
            nvOoLCH7mY2+UW1RprVUK0iEoAXeyB44A4O8hQU9hdJeAVMN4H4A4FhT6X69QfDI
            hLWED7LLwmwgD/qEyAt+E6KIKiExVknz4Ql/aRzNZK5ozEiXH6JtmBkHz+ipaFRA
            lLPm8IFeg1sqZc3BSxamngRrcho2qmKomfG+UrXrBg==
            =Hu4F
            -----END PGP MESSAGE-----
        fp: 02B688797D1B649A6FB352756E8AC191164F2E1D
    unencrypted_suffix: _unencrypted
    version: 3.5.0
