baseResources:
  serviceAccounts:
  - name: triggers
  - name: ci-builder
  clusterRoles:
  - name: triggers
    rules:
    - apiGroups:
      - triggers.tekton.dev
      resources:
      - eventlisteners
      - triggerbindings
      - clustertriggerbindings
      - triggertemplates
      verbs:
      - get
    - apiGroups:
      - tekton.dev
      resources:
      - pipelineruns
      - pipelineresources
      verbs:
      - create
    - apiGroups:
      - '""'
      resources:
      - configmaps
      - secrets
      verbs:
      - get
      - create
      - list
      - watch
  - name: ci-builder
    rules:
    - apiGroups:
      - '""'
      resources:
      - configmaps
      - services
      verbs:
      - get
      - list
      - create
      - watch
      - update
      - patch
      - delete
    - apiGroups:
      - 'extensions'
      - 'networking.k8s.io'
      resources:
      - ingresses
      verbs:
      - get
      - list
      - create
      - watch
      - update
      - patch
      - delete
    - apiGroups:
      - 'apps'
      resources:
      - deployments
      verbs:
      - get
      - create
      - list
      - watch
      - update
      - patch
      - delete
  clusterRoleBindings:
  - name: triggers
    serviceAccountName: triggers
    serviceAccountNamespace: default
    clusterRoleName: triggers
  roleBindings:
  - name: ci-builder
    namespace: deployments
    serviceAccountName: ci-builder
    serviceAccountNamespace: default
    clusterRoleName: ci-builder
