apiVersion: v2
name: external-dns
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: 1.16.0
dependencies:
- name: external-dns
  version: 3.4.8
  repository: https://charts.bitnami.com/bitnami
