baseResources:
    secrets:
    -   name: ENC[AES256_GCM,data:uaBQ+FyEn1xgduLWiuWUPA==,iv:rmOMSsvtM3EWAfis5DC41MxOw/uK3IxlpMtLqeG6wHM=,tag:VFYB6sfbRMPEPFK3jDoHJQ==,type:str]
        fields:
            cloudflare_api_token: ENC[AES256_GCM,data:QRiFXdVAPRwPl5ppc29CauSMCQDjURz+r49Rso60plIKafpqXr5H5Q==,iv:Lz1zfKLbYOvE49QwAT7JsZ2RhO43m+1WgDL518d/ZWA=,tag:1SjEuo4M55qcRjsWqUY09g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-10-18T15:18:52Z'
    mac: ENC[AES256_GCM,data:qq93a+c37lfdOr4Gu0XrZCDichXA0v4WYj6621K9YEz5mNqGTQjLpcOFFRT7abaykJHlfdQsZzN4ibFpOt235cCqEcTBAfn1D/JUR0g6NRAzZQTCi3PaElZ2t64j6MRUfXcF42LSKscTr6e98PYaSd3sz8h5ivVslRAp/cIsLXg=,iv:WwjZaV0eRLlYuVchWh05HtS1D6rF7wuw5PmEXvc/EkU=,tag:7FEyT95CGZCk7+XyJRaTyQ==,type:str]
    pgp:
    -   created_at: '2020-10-18T15:18:51Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA1Biv9gnCd8SAQgAoXWARHtBTeORIalZDJ8U4LYJH0tfZ2eeZ5ieoXZP6lEB
            PztEhar+5WbS47Z1dAErWE39Bru2rXRzcpsHl0qbbNRm0qp8OmAuYKPTp+0uqHNg
            /Yh/B4qZ3zaU3Ktw8iVswxo7VFKrOaxvCwBFX2h1zCp54RUg9/aLjgh6QIa4TvkN
            etDFbLeMFKYJ8xyPESdEh84lMrXMMeu8dy5UW585rdHhPmCRePwL7Ek4+jtT862G
            6NIFNNIFYW+wpyRk2dORgc3iYoK6h2AiDks5siugUJVQ/5yNwSc/vlYu32tqlq1e
            N3q90aqV/k7sjn+GeG4rl7Cvzxff56U/yMEo+pa2KtJcAQZk5I9hxclZwgpXWfes
            i2wK7JQnnwzuKMOxnmTlaVP++16I9luvXl2tLK+fQO50GM/obHVpc4BdcAclJ7EF
            YuugUO14gejTG96V9J5g/dQr+UrGqDXdAf+0NKA=
            =S6S4
            -----END PGP MESSAGE-----
        fp: 02B688797D1B649A6FB352756E8AC191164F2E1D
    unencrypted_suffix: _unencrypted
    version: 3.6.1
