apiVersion: v2
name: matrix
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: 1.16.0
dependencies:
  - name: base
    version: 0.1.0
    repository: file://../base
