{{- define "base.certificates" -}}
{{- range $index, $certificate := .Values.baseResources.certificates }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $certificate.name }}
  namespace: {{ $certificate.namespace }}
spec:
  dnsNames:
  {{- range $domain := $certificate.domains }}
  - '{{ $domain }}'
  {{- end }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ include "base.name" $ }}
  secretName: {{ $certificate.name }}
---
{{- end }}
{{- end -}}
