{{- define "base.clusterIssuer" -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ include "base.name" . }}
spec:
  acme:
    dns01:
      providers:
      - name: cloudflare
        cloudflare:
          email: paul@paul-steele.com
          apiKeySecretRef:
            name: {{ .Values.baseResources.clusterIssuer.secretName }}
            key: key
    email: paul-steele@live.com
    privateKeySecretRef:
      name: letsencrypt-cert-manager
    server: https://acme-v02.api.letsencrypt.org/directory
{{- end -}}
