{{- define "base.clusterIssuer" -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "base.name" . }}
spec:
  acme:
    solvers:
    - dns01:
        cloudflare:
          email: paul@paul-steele.com
          apiTokenSecretRef:
            name: {{ .Values.baseResources.clusterIssuer.secretName }}
            key: cloudflare_api_token
    email: paul-steele@live.com
    privateKeySecretRef:
      name: letsencrypt-cert-manager
    server: https://acme-v02.api.letsencrypt.org/directory
{{- end -}}
