{{- define "base.ingress" -}}
{{- if .Values.baseResources.ingress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: '0'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      access_log /var/log/nginx/access.log;
      access_log /logs/{{ include "base.name" . }}.log;
    {{- if .Values.baseResources.ingress.auth }}
    nginx.ingress.kubernetes.io/auth-url: "https://sso.paul-steele.com/api/verify"
    nginx.ingress.kubernetes.io/auth-signin: "https://sso.paul-steele.com/"
    {{- end }}
  name: {{ include "base.name" . }}
spec:
  rules:
  - host: {{ .Values.baseResources.ingress.host }}
    http:
      paths:
      {{- if .Values.baseResources.ingress.extraPaths }}
      {{- $root := . -}}
      {{- $serviceName := .Values.baseResources.ingress.serviceName -}}
      {{- range $index, $path := .Values.baseResources.ingress.extraPaths }}
      - backend:
          serviceName: {{ default ( include "base.name" $root ) $serviceName }}
          servicePort: {{ $path.port }}
        path: {{ $path.path }}
      {{- end }}
      {{- end }}
      - backend:
          serviceName: {{ default ( include "base.name" . ) .Values.baseResources.ingress.serviceName }}
          servicePort: {{ .Values.baseResources.ingress.port }}
        path: /
  tls:
  - hosts:
    - {{ .Values.baseResources.ingress.host }}
{{- end }}
{{- if .Values.baseResources.ingresses }}
{{- range $index, $ingress := .Values.baseResources.ingresses }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: '0'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      access_log /var/log/nginx/access.log;
      access_log /logs/{{ $ingress.name }}.log;
    {{- if $ingress.auth }}
    nginx.ingress.kubernetes.io/auth-url: "https://sso.paul-steele.com/api/verify"
    nginx.ingress.kubernetes.io/auth-signin: "https://sso.paul-steele.com/"
    {{- end }}
  name: {{ $ingress.name }}
spec:
  rules:
  - host: {{ $ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ $ingress.serviceName }}
          servicePort: {{ $ingress.port }}
        path: /
  tls:
  - hosts:
    - {{ $ingress.host }}
---
{{- end }}
{{- end }}
{{- end -}}
