apiVersion: v2
name: postgres
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.15.0
dependencies:
- name: base
  version: 0.1.0
  repository: file://../base
- name: postgres-operator
  version: 0.1.0
  repository: git+https://github.com/CrunchyData/postgres-operator.git@installers/helm?ref=fda8a52b665dcc1bdcc7e27529ad8fca7f19ed12 
